ev3_hacks: include sys/types.h
Fixes failing build due to:

    In file included from /home/david/work/pybricks/pybricks-micropython/lib/ev3rt-lib/target/ev3_gcc/drivers/common/include/driver_common.h:28,
                    from /home/david/work/pybricks/pybricks-micropython/lib/ev3rt-lib/target/ev3_gcc/platform/include/csl.h:11,
                    from /home/david/work/pybricks/pybricks-micropython/lib/ev3rt-lib/target/ev3_gcc/ev3.cfg:1:
    /home/david/work/pybricks/pybricks-micropython/lib/ev3rt-lib/target/ev3_gcc/drivers/common/include/ev3_hacks.h:102:42: error: unknown type name 'clockid_t'
    102 | void hrtimer_init(struct hrtimer *timer, clockid_t which_clock, enum hrtimer_mode mode);
        |                                          ^~~~~~~~~